---
name: Build tuqueOS ISO

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64
  pull_request:
    branches:
      - main
    paths:
      - "./.github/workflows/build-iso.yml"
      - "./disk_config/iso.toml"

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ISOs
    runs-on: ${{ inputs.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: lower case the image registry in case of any capitalization
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}

      - name: Install dependencies
        if: inputs.platform == 'arm64'
        run: |
          set -x
          sudo apt update -y
          sudo apt install -y \
            podman

      - name: Maximize build space
        if: inputs.platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          image_name: tuqueos-el
          image_repo: ghcr.io/shaunassam
          image_tag: latest
          flatpak_remote_url: https://flathub.org/repo/flathub.flatpakrepo
          flatpak_remote_name: flathub
          flatpak_remote_refs: org.mozilla.firefox/x86_64/stable org.mozilla.Thunderbird/x86_64/stable com.mattjakeman.ExtensionManager com.ranfdev.DistroShelf/x86_64/stable app/org.gnome.Firmware/x86_64/stable app/com.github.tchx84.Flatseal/x86_64/stable
          variant: Server
          version: 42
          iso_name: build/tuqueos-el.iso

     # - name: Rename and Checksum ISO
        #run: |
          #mkdir -p output
          #mv ${{ steps.build.outputs.iso_path }} output/tuqueos.iso
          #(cd output && sha256sum tuqueos.iso | tee tuqueos.iso-CHECKSUM)

      - name: Upload ISOs and Checksum to Job Artifacts
        if: inputs.upload-to-s3 != true && github.event_name != 'pull_request'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: tuqueos-el
          path: |
            build/tuqueos-el.iso
            build/tuqueos-el.iso-CHECKSUM
          if-no-files-found: error
          retention-days: 3
          compression-level: 0
          overwrite: true

      # - name: Build ISO
      #   id: build
      #   uses: ublue-os/titanoboa@main
      #   with:
      #     image-ref: ghcr.io/shaunassam/tuqueos-el:latest
      #     flatpaks-list: ${{ github.workspace }}/flatpaks/flatpaks.list
      #     hook-post-rootfs: ${{ github.workspace }}/iso_files/configure-el-iso-anaconda.sh
      #     kargs: ""
      #     builder-distro: centos

      # - name: Rename and Checksum ISO
      #   run: |
      #     mkdir -p output
      #     mv ${{ steps.build.outputs.iso-dest }} output/tuqueos-el.iso
      #     (cd output && sha256sum tuqueos-el.iso | tee tuqueos-el.iso-CHECKSUM)

      # - name: Upload ISOs and Checksum to Job Artifacts
      #   if: inputs.upload-to-s3 != true && github.event_name != 'pull_request'
      #   uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      #   with:
      #     name: tuqueos-el
      #     path: output
      #     if-no-files-found: error
      #     retention-days: 3
      #     compression-level: 0
      #     overwrite: true